Repository GSA/challenges-and-prizes, pull requests merged in 2020-05, with the labels that each got.

#673 Update Challenge “1120-project-streetlamp”
  _challenges/1120-project-streetlamp.md
  assets/netlify-uploads/labcftc_competition_web.jpg
Labels: netlify-cms/pending_publish

#674 Update Challenge “1047-rodeo-ii-sub-seasonal-climate-forecasting”
  _challenges/1047-rodeo-ii-sub-seasonal-climate-forecasting.md
Labels: netlify-cms/pending_publish

#672 Update Challenge “90-individuals-taking-energy-action-in-manufacturing”
  _challenges/90-individuals-taking-energy-action-in-manufacturing.md
Labels: netlify-cms/pending_publish

#676 Update Challenge “1101-network-detection-of-adversarial-campaigns”
  _challenges/1101-network-detection-of-adversarial-campaigns.md
Labels: netlify-cms/pending_publish

#682 Update Challenge “1116-lithium-battery-portable-hazard-containment-challenge”
  _challenges/1116-lithium-battery-portable-hazard-containment-challenge.md
Labels: netlify-cms/pending_publish

#688 Create Challenge “1126-covid-19-3d-maker-challenge”
  _challenges/1126-covid-19-3d-maker-challenge.md
  admin/config.yml
  assets/netlify-uploads/covid-19_maker_challenge.png
  assets/netlify-uploads/covidmaker.png
Labels: netlify-cms/draft

#689 Update Challenge “1122-inclusive-design-challenge”
  _challenges/1122-inclusive-design-challenge.md
Labels: netlify-cms/pending_publish

#695 Create Challenge “1127-mit-covid-19-challenge-beat-the-pandemic-ii”
  _challenges/1127-mit-covid-19-challenge-beat-the-pandemic-ii.md
  assets/netlify-uploads/beat-the-pandemic-2.png
Labels: netlify-cms/pending_publish

#697 Update Challenge “1124-truth-challenge-v2-calling-variants-from-short-and-long-reads-in-difficult-to-map-regions”
  _challenges/1124-truth-challenge-v2-calling-variants-from-short-and-long-reads-in-difficult-to-map-regions.md
Labels: netlify-cms/pending_publish

#696 Create Challenge “1128-vha-innovation-ecosystem-and-precisionfda-covid-19-risk-factor-modeling-challenge”
  _challenges/1128-vha-innovation-ecosystem-and-precisionfda-covid-19-risk-factor-modeling-challenge.md
  assets/netlify-uploads/vha-fda-resize.png
  assets/netlify-uploads/vha-fda.png
Labels: netlify-cms/pending_publish

#698 Create Challenge “1129-nih-prize-for-enhancing-faculty-gender-diversity-in-biomedical-and-behavioral-science”
  _challenges/1129-nih-prize-for-enhancing-faculty-gender-diversity-in-biomedical-and-behavioral-science.md
Labels: netlify-cms/pending_review

#711 Create Challenge “1130-civic-innovation-challenge”
  _challenges/1130-civic-innovation-challenge.md
  assets/netlify-uploads/civic-innovation-340x160.png
Labels: netlify-cms/pending_publish

#718 Update Challenge “1127-mit-covid-19-challenge-beat-the-pandemic-ii”
  _all-challenges/1127-mit-covid-19-challenge-beat-the-pandemic-ii.md
Labels: netlify-cms/pending_publish

#719 Create Challenge “1131-ahrq-cross-sectional-innovation-to-improve-rural-postpartum-mental-health-challenge”
  _all-challenges/1131-ahrq-cross-sectional-innovation-to-improve-rural-postpartum-mental-health-challenge.md
  assets/netlify-uploads/ahrq_hhs-brand_color-340x160-.jpg
Labels: netlify-cms/pending_publish

#721 Update Challenge “1127-mit-covid-19-challenge-beat-the-pandemic-ii”
  _all-challenges/1127-mit-covid-19-challenge-beat-the-pandemic-ii.md
Labels: netlify-cms/pending_publish
